python train_decoding.py --model_name MultiViewBrainTranslator ^
    --task_name task1_task2_taskNRv2 ^
    --one_step ^
    --pretrained ^
    --not_load_step1_checkpoint ^
    --num_epoch_step1 20 ^
    --num_epoch_step2 30 ^
    -lr1 0.00005 ^
    -lr2 0.0000005 ^
    -b 4 ^
    -s ./checkpoints/decoding ^
    -cuda cuda:0